data:
  raw_csv: data/raw/weatherAUS.csv
  interim_csv: data/interim/df_preprocessed.csv
  processed_dir: data/processed
  X_train: data/processed/X_train.csv
  X_test: data/processed/X_test.csv
  y_train: data/processed/y_train.csv
  y_test: data/processed/y_test.csv
  test_size: 0.2
  random_state: 42
  split_id: 2
model:
  type: xgboost
  max_depth: 9
  learning_rate: 0.05
  n_estimators: 200
  colsample_bytree: 0.8
  subsample: 0.7
  gamma: 0.1
  min_child_weight: 3
  random_state: 42
database:
  host: mongodb
  port: 27017
  username: admin
  password: password123
  db_name: weather_db
  collection: weather_data
mlflow:
  tracking_uri: http://mlflow:5000
  experiment_name: weather-au-rain
features:
  target: RainTomorrow
  drop_cols:
  - RISK_MM
